# Generated by Django 5.2.13 on 2026-04-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Draft', 'Draft'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobtrackapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('cv_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Reviewed', 'Reviewed'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Contract', 'Contract'), ('Rejected', 'Rejected')], default='Reviewed', max_length=10)),
                ('applied_at', models.DateField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobtrackapp.offer')),
            ],
        ),
    ]
