# Generated by Django 5.2.13 on 2026-04-26 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtrackapp', '0002_company_author_offer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv_link',
        ),
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
